### ISSUE TITLE
有关实验训练设置相关问题

### ISSUE THREAD

**Issue by Vermouth145** [wenxinss/DR-YOLO#1]
实验中和IA-YOLO一样，先离线合成四种带雾程度的foggy images，训练时从四种等级的带雾图中随机2/3的概率加载一张，VF-train就是混合了normal和foggy的图像，VF-test也是随机选出来的，和IA-YOLO使用的测试集相同。另外，论文table3中的结果貌似比IA-YOLO原文report的结果高出许多，是因为AP@.5和AP@.5-.95的区别么？以上是个人理解，希望您能解答我的困惑

**Comment by wenxinss** [comment]
训练集是从VOC数据集中筛选出来的，帅选方式和IA-YOLO一致，共筛选出8111张原始干净的图像。

- 关于IA-YOLO：

1. 作者的方法是离线生成10个等级的雾，然后加载数据集的时候以1/3的概率从离线生成的雾图中拿到一个，因此在训练中使用到的图像数量为8111张图像。
2. IA-YOLO在解释评价指标中引用了VOC2012文献，因此使用的应为VOC2012评价方法。

- 关于DR-YOLO：

1. 我们followIA-YOLO生成数据集，但是我们生成了4个尺度的。此外，我们将生成的这4个尺度的图像全部作为训练集，即有4×8111=32444张图像作为训练集（这在论文中是有描述的）。
2. 在我们生成的数据集中分别训练测试SOTA模型包括IA-YOLO，因此这里使用的数据集相对于IA-YOLO多了3倍。
3. 在计算所有方法的AP时，使用的都是AP@.5。

**Comment by Vermouth145** [comment]
谢谢解答，受益匪浅。另外，VOC_Foggy_test和IA-YOLO是保持一致的吗（IA-YOLO相关code中按照voc_fog_test.txt固定了测试集，即VOC_Normal_test对应的foggy程度也固定下来了），还是说是您文中描述的测试集挑选方案和IA-YOLO一致是指“随机挑选这个思路一致，而不是测试集完全一致”，即从四种程度的VOC_Foggy_test中随机选取一种？

**Comment by wenxinss** [comment]
感谢您对本工作的关注。是这样的，VOC_Foggy_test在IA-YOLO的GitHub中有提供，所以测试集这块和IA-YOLO是一致的。具体可见https://github.com/wenyyu/Image-Adaptive-YOLO#datasets-and-models

**Comment by Vermouth145** [comment]
ok谢谢！很好的工作，祝后续工作也都顺利！
